### ISSUE TITLE
Zones don't show up in plugin config - can't create a server page/menu

### ISSUE THREAD

**Issue by Saikodesu** [Moc/teamspeak3#3]
I've added zones to multiple areas on the site trying to get the creator to acknowledge that they are active (and thus usable) to no avail.

The ddl for zone selection is perpetually empty.

Not sure if this was something that was changed in how the pages are registered active or whatnot but.. yours is about the only 2.0 viewer i've found so far.. XD

i don't know enough about php to sort it out else i'd try.  hope it's something easy for you.

**Comment by Moc** [comment]
I'll look into this as soon as possible (probably tomorrow)

**Comment by Moc** [comment]
Hi there, 

I'm having some difficulties understanding the problem. Could you please clarify what you mean by the following:

> trying to get the creator to acknowledge that they are active

and

> ddl for zone selection is perpetually empty

The steps to add a viewer are:
- Install the plugin
- Place the TeamSpeak zones on your website by activating the zone menus in the menu manager
- Add the TeamSpeak server, and assign it to a zone
- The server should show up in the menu area you activated the zone menu in. 

As I haven't worked on this plugin for a while anymore, I'm not sure if it's still working properly. I'll run some tests as well on the latest version of v2 to see if it still works like it should.

**Comment by Moc** [comment]
Perhaps the installation went wrong:

- Download the ZIP by hitting the 'Download ZIP' button here on the right hand side: https://github.com/moc/teamspeak3
- Extract the files and make sure the folder name is teamspeak3 (it may be teamspeak3-master when you downloaded it, so be sure to rename it)
- Upload the teamspeak3 folder to your website (e107_plugins folder) 
- Then install the plugin through the plugin manager

**Comment by Saikodesu** [comment]
It was the folder name that was causing the problem.  Seems it was wrong to name it something else (i had a bunch of other ones loaded trying to get them  to work so i renamed the folder for a bit more description.  Issues is resolved.

**Comment by Moc** [comment]
I'm glad the issue is sorted out. Please do let me know how you like the plugin. I'm welcoming additional feature requests or ideas to be implemented, so feel free to give some feedback!

**Comment by Saikodesu** [comment]
really liking how easy it is to manage the ts after i got everything up and
running.

Was wondering if you'd be including maybe a built-in sizing option for the
text etc or should i stick with trying to figure out the css? :)

**Comment by Moc** [comment]
I am looking into some easy ways to template / style the viewer, it's on the roadmap :) 

For now, you can edit the e_header.php file. Would you mind sharing the website you are using the plugin on? I'm interested to see its application.

**Comment by Saikodesu** [comment]
Right now it's just on the front page of our new community gaming site.

Mayhemmilitia.wtf

My php experience is what you'd call limited lol

For now it's just a slightly modified bootstrap

**Comment by Saikodesu** [comment]
would it be possible to work in a join link on the header?

**Comment by Moc** [comment]
I've added a connect button :) Update the files from Github and it should be there.

**Comment by Saikodesu** [comment]
for whatever reason.. i'm not seeing a button showing up after installing
the new files :(

**Comment by Saikodesu** [comment]
ahhh, my bad - i should have checked preferences first!
