### ISSUE TITLE
Zone Box Empty

### ISSUE THREAD

**Issue by Buckfutt** [Moc/teamspeak3#4]
Zone Combo box is empty, can not add a server without this section being filled.

**Comment by Moc** [comment]
I suspect something went wrong with the installation. Probably the plugin folder name is 'teamspeak3-master'. In that case, rename it to 'teamspeak3'. 

Here are the full instructions:

- Download the ZIP by hitting the 'Download ZIP' button here on the right hand side: https://github.com/moc/teamspeak3
- Extract the files and make sure the folder name is teamspeak3 (it may be teamspeak3-master when you downloaded it, so be sure to rename it)
- Upload the teamspeak3 folder to your website (e107_plugins folder) 
- Then install the plugin through the plugin manager

Let me know if this solves the issue.

**Comment by Buckfutt** [comment]
totally fixed it, i accidentally deleted the "3" from the folder name.
Thanks much!

**Comment by Moc** [comment]
@Buckfutt Great! Let me know how you like the plugin and if you're missing any features. Feature requests are welcome.
